kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pre-producao-read-access
  namespace: pre-producao
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "watch", "list"]