kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: desenvolvedores-homologacao-full-access
  namespace: homologacao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: homologacao-full-access
subjects:
- kind: Group
  namespace: homologacao
  name: groupObjectId
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lideres-homologacao-full-access
  namespace: homologacao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: homologacao-full-access
subjects:
- kind: Group
  namespace: homologacao
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: arquitetos-full-access
  namespace: homologacao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: homologacao-full-access
subjects:
- kind: Group
  namespace: homologacao
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
