kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: desenvolvedores-producao-read-access
  namespace: producao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: producao-read-access
subjects:
- kind: Group
  namespace: producao
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lideres-producao-read-access
  namespace: producao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: producao-read-access
subjects:
- kind: Group
  namespace: producao
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: arquitetos-full-access
  namespace: producao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: producao-full-access
subjects:
- kind: Group
  namespace: producao
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
