kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: desenvolvedores-desenvolvimento-full-access
  namespace: desenvolvimento
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: desenvolvimento-full-access
subjects:
- kind: Group
  namespace: desenvolvimento
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: lideres-desenvolvimento-full-access
  namespace: desenvolvimento
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: desenvolvimento-full-access
subjects:
- kind: Group
  namespace: desenvolvimento
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: arquitetos-full-access
  namespace: desenvolvimento
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: desenvolvimento-full-access
subjects:
- kind: Group
  namespace: desenvolvimento
  name: bfe38006-b3e6-4228-93cf-48f85906fb3b
